### ISSUE TITLE
 GSA.ToolKits.DBUtility.TDengine    winform 程序窗口事件中调用。一直卡着不动，在Program.cs中写可以，这个是为什么

### ISSUE THREAD

**Issue by 759085503** [cockroach888/GSA.MOLLE.ToolKits#2]
winform 程序窗口事件总调用。一直卡着不动，在Program.cs中写可以，这个是为什么？                                                                                      
           var version = (await Connection.ExecuteRequestResultAsync(new TDengineQueryParam($"SELECT SERVER_VERSION()")));
            Version version2 = new Version(version.Data.Root[0][0].ToString());
            return version2.Major;

**Comment by 759085503** [comment]
var Connection= TDengineConnectorProvider.Default.Create(new TDengineOptions()
                {
                    Host = DataSource,
                    Password = password,
                    Port = Port,
                    UserName = userName,
                    TimeZone = "Asia/Shanghai",
                    VersionSelector = TDengineVersion.V3,
                    KeyNameRegex = new[]
                    {  "last_row\\((.+?)\\)",
                        "last\\((.+?)\\)",
                        "first\\((.+?)\\)",
                        "avg\\((.+?)\\)",
                        "max\\((.+?)\\)",
                        "min\\((.+?)\\)",
                        "sum\\((.+?)\\)"
                    }
                });

**Comment by cockroach888** [comment]
是直接使用Provider创建出一个连接使用对吧？
WinForm 对应的框架版本是多少？.net 9？还是？

**Comment by cockroach888** [comment]
是直接使用Provider创建出一个连接使用对吧？

**Comment by cockroach888** [comment]
我写了一个示例程序，并没有发现存在任何问题。
https://github.com/cockroach888/GSA.MOLLE.ToolKits/tree/main/src/samples/TaosData/TDengineEx.Appx4WinForm/src

请确认你的代码是如何编写的！
